import { useState } from 'react';
import { ExternalLink, Search } from 'lucide-react';
import type { AppState, Source, SourceCheck } from '../../shared/models';
import { bridge } from '../bridge';
export function SourceCatalog({state,onError}:{state:AppState;onError:(message:string)=>void}){
  const [query,setQuery]=useState(''),[group,setGroup]=useState('All'),[availability,setAvailability]=useState('all'),[sort,setSort]=useState('findings'),[selected,setSelected]=useState<string|null>(null),[checks,setChecks]=useState<SourceCheck[]>([]),[loading,setLoading]=useState(false);
  const findings=(source:Source)=>state.happenings.filter(h=>h.sourceId===source.sourceId||h.sourceUrl===source.url||h.relatedSources.some(reference=>reference.url===source.url)).length;
  const grouped=(s:Source)=>{const text=[s.name,s.domain].join(' ');const records=state.happenings.filter(h=>h.sourceId===s.sourceId);return group==='All'||group==='Government'&&(s.type==='OFFICIAL'||/government|council|city hall/i.test(text))||group==='News'&&(s.type==='NEWS'||/news|times|current|wthr|magazine/i.test(text))||group==='Community'&&(s.type==='COMMUNITY'||records.some(h=>h.category==='community'))||group==='Venues'&&/venue|arena|event center|music|theater|theatre|concert/i.test(text)||group==='Transportation'&&(/transport|traffic|highway|transit/i.test(text)||records.some(h=>h.category==='traffic'))||group==='Schools & libraries'&&/school|university|library|college/i.test(text);};
  const sources=state.sources.filter(s=>grouped(s)&&(availability==='all'||(s.status||'idle')===availability)&&[s.name,s.domain].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='findings'?findings(b)-findings(a):sort==='name'?a.name.localeCompare(b.name):(b.lastChecked||'').localeCompare(a.lastChecked||''));
  async function inspect(s:Source){if(selected===s.sourceId){setSelected(null);return;}setSelected(s.sourceId);setLoading(true);setChecks([]);try{setChecks(await bridge.sourceHistory(s.sourceId));}catch(error){onError(String(error));}finally{setLoading(false);}}
  return <section className="source-catalog"><div className="source-catalog-controls"><label><Search size={14}/><input aria-label="Search source catalog" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a publisher…"/></label><select aria-label="Source group" value={group} onChange={e=>setGroup(e.target.value)}>{['All','Government','News','Community','Venues','Transportation','Schools & libraries'].map(name=><option key={name}>{name}</option>)}</select><select aria-label="Source availability" value={availability} onChange={e=>setAvailability(e.target.value)}>{['all','healthy','failed','blocked','idle'].map(name=><option key={name}>{name}</option>)}</select><select aria-label="Sort sources" value={sort} onChange={e=>setSort(e.target.value)}><option value="findings">Most findings</option><option value="checked">Last checked</option><option value="name">Publisher name</option></select><span>{sources.length} sources</span></div><p className="field-help">Groups use publisher names and collected categories. Authority comes from the recorded source classification and evidence.</p><div className="catalog-heading"><span>Publisher</span><span>Class / format</span><span>Availability</span><span>Findings</span><span>Last checked</span><span/></div>{sources.map(s=><article className="catalog-source" key={s.sourceId}><div className="catalog-source-row"><button onClick={()=>void inspect(s)} aria-expanded={selected===s.sourceId}><strong>{s.name}</strong><small>{s.domain}</small></button><span>{s.type}<small>{s.parserType} · Every {Math.round(s.checkFrequency/3600*10)/10}h</small></span><span className={`source-status status-${s.status||'idle'}`}>{s.status||'not checked'}</span><span>{findings(s)}</span><time>{s.lastChecked?new Date(s.lastChecked).toLocaleString():'Not yet'}</time><button aria-label={`Visit ${s.name}`} onClick={()=>void bridge.openExternal(s.url).catch(e=>onError(String(e)))}><ExternalLink size={14}/></button></div>{selected===s.sourceId&&<div className="source-check-history"><p>{s.notes||'No additional discovery notes.'}</p>{s.lastError&&<p className="form-error">Last error: {s.lastError}</p>}<p>Next check: {s.nextCheckAt?new Date(s.nextCheckAt).toLocaleString():'When due'}</p>{loading?<p>Reading local check history…</p>:checks.length?checks.map((check,i)=><div key={i}><time>{new Date(check.checkedAt).toLocaleString()}</time><strong>{check.status}</strong><span>{check.recordsFound} records · {Math.round((check.durationMs||0)/1000*10)/10}s · {check.httpStatus?`HTTP ${check.httpStatus}`:'No HTTP response'}</span>{check.error&&<small>{check.error}</small>}</div>):<p>No check history recorded.</p>}</div>}</article>)}{!sources.length&&<p className="honest-empty">No publishers match. Add a public local source or run deeper discovery.</p>}</section>;
}
