// Opt-in, robots-aware capture of short source excerpts for deterministic tests.
import { writeFileSync } from 'node:fs';
import ICAL from 'ical.js';
import { load } from 'cheerio';
import { PublicHttp } from '../src/backend/collectors/http';
import { extract } from '../src/backend/extraction';
import { plainText } from '../src/backend/parsers/common';

const http = new PublicHttp();
const publisherUrl = 'https://www.shoreline.edu/calendars/mobile-devices.aspx';
const publisher = await http.request(publisherUrl);
if (publisher.status !== 200) throw Error('Publisher unavailable');
const now = new Date().toISOString(); const timezone = 'America/Los_Angeles';
const advertised = extract(publisher.body, publisher.url, publisher.contentType, now, timezone);
const icsUrl = advertised.discoveredLinks.find(link => link.url.endsWith('/sccevents.ics'))?.url;
const jsonUrl = advertised.discoveredLinks.find(link => link.url.endsWith('/sccevents.json'))?.url;
if (!icsUrl || !jsonUrl) throw Error('Publisher did not advertise a supported calendar subscription');
const $ = load(publisher.body);
const listItem = $('li').filter((_, node) => $(node).text().includes('sccevents.ics')).get().sort((a, b) => $(a).text().length - $(b).text().length)[0];
if (!listItem) throw Error('Missing published subscription text');
writeFileSync('tests/fixtures/ingestion/shoreline-calendar-publisher-live.html', `<!doctype html><html><body><!-- Source: ${publisher.url} | Retrieved: ${now} -->${$(listItem).toString()}</body></html>\n`);
const calendar = await http.request(icsUrl); if (calendar.status !== 200) throw Error('Calendar unavailable');
const records = extract(calendar.body, calendar.url, calendar.contentType, now, timezone).records;
const original = new ICAL.Component(ICAL.parse(calendar.body));
const selected = original.getAllSubcomponents('vevent').find(component => component.getFirstPropertyValue('uid') === records[0]?.rawMetadata?.uid);
if (!selected) throw Error('No current source event');
const excerpt = new ICAL.Component('vcalendar'); excerpt.addPropertyWithValue('version', '2.0');
for (const zone of original.getAllSubcomponents('vtimezone')) excerpt.addSubcomponent(new ICAL.Component(structuredClone(zone.toJSON())));
const event = new ICAL.Component('vevent');
for (const property of selected.getAllProperties()) if (['uid', 'summary', 'dtstamp', 'dtstart', 'dtend', 'duration', 'rrule', 'rdate', 'exdate', 'geo', 'url', 'location', 'categories'].includes(property.name)) event.addProperty(new ICAL.Property(structuredClone(property.toJSON())));
event.addPropertyWithValue('description', plainText(selected.getFirstPropertyValue('description'), 240));
excerpt.addSubcomponent(event);
writeFileSync('tests/fixtures/ingestion/shoreline-calendar-live.ics', excerpt.toString() + '\r\n');
const json = await http.request(jsonUrl); if (json.status !== 200) throw Error('Public calendar JSON unavailable');
const all = JSON.parse(json.body) as Record<string, unknown>[];
const first = all.find(record => record.title === records[0]?.title); if (!first) throw Error('No equivalent JSON source event');
const safe = Object.fromEntries(Object.entries(first).filter(([key]) => ['eventID', 'title', 'locationType', 'location', 'webLink', 'startDateTime', 'endDateTime', 'allDay', 'startTimeZoneOffset', 'endTimeZoneOffset', 'canceled', 'permaLinkUrl'].includes(key)));
safe.description = plainText(first.description, 240);
writeFileSync('tests/fixtures/ingestion/shoreline-calendar-live.json', JSON.stringify([safe], null, 2) + '\n');
const evidence = { capturedAt: now, publisherUrl: publisher.url, discovery: advertised.discoveredLinks.filter(link => link.url === icsUrl || link.url === jsonUrl), ics: { url: calendar.url, status: calendar.status, records: records.length, title: records[0].title }, json: { url: json.url, status: json.status, records: extract(json.body, json.url, json.contentType, now, timezone).records.length }, robotsPolicy: 'PublicHttp.request default robots checks on every origin/path' };
writeFileSync('tests/fixtures/ingestion/shoreline-calendar-live-attribution.json', JSON.stringify(evidence, null, 2) + '\n');
console.log(JSON.stringify(evidence));
