import {describe,it,expect} from 'vitest';
import {assessConfidence,meaningfulChanges,samePublisherIdentity,sameResearchSubject} from '../src/backend/research/confidence';
import {calculateCoverage,observedRelationships} from '../src/backend/research/pulse';
import {parsePublicPosts} from '../src/backend/discovery/posts';
import {testHappenings} from './fixtures/test-records';
import { testSettings as defaultSettings } from './fixtures/test-records';
import {evidenceFromHappening} from '../src/shared/intelligence';
import {LocalDatabase} from '../src/backend/database';
import type {Happening} from '../src/shared/models';
const now='2026-09-30T15:00:00Z';const h=(extra:Partial<Happening>={}):Happening=>({...testHappenings[0],id:'event',isDemo:false,sourceId:'publisher',sourceUrl:'https://venue.example/events/1',title:'Local makers festival',startTime:'2026-10-02T19:00:00Z',endTime:'2026-10-02T23:00:00Z',locationName:'Town Hall',publishedAt:null,lastVerifiedAt:now,updatedAt:now,rawMetadata:{uid:'one',format:'jsonld'},...extra});
describe('recorded evidence intelligence',()=>{
 it('does not invent clock times or join similar undated announcements',()=>{const dateOnly=evidenceFromHappening(h({allDay:true}));const score=assessConfidence('event',[dateOnly,{...dateOnly,id:'other',sourceUrl:'https://other.example/date',independentGroup:'other.example'}],now);expect(score.factors.some(f=>f.key==='independent'||f.key==='consistent')).toBe(false);expect(score.uncertainties.join()).toContain('date-only');expect(sameResearchSubject(h({title:'District notice 1',startTime:null}),h({title:'District notice 2',startTime:null}))).toBe(false);});
 it('does not turn retrieval recency or duplicate domains into corroboration',()=>{const first=evidenceFromHappening(h());const other=evidenceFromHappening(h({sourceUrl:'https://www.venue.example/events/2'}));const result=assessConfidence('event',[first,other],now);expect(result.factors.some(f=>f.key==='recent'||f.key==='independent')).toBe(false);expect(result.uncertainties.join()).toContain('Publication recency is unknown');expect(result.score).toBeLessThanOrEqual(80);});
 it('uses independently published dates and preserves conflicting claims',()=>{const first=evidenceFromHappening(h({sourceType:'ORGANIZATION',publishedAt:now}));const second=evidenceFromHappening(h({sourceUrl:'https://organizer.example/1',sourceType:'ORGANIZATION',publishedAt:now}));expect(assessConfidence('event',[first,second],now).factors.some(f=>f.key==='independent')).toBe(true);const conflict=assessConfidence('event',[first,{...second,startTime:'2026-10-02T20:00:00Z',cancelled:true}],now);expect(conflict.contradictions.map(c=>c.field)).toEqual(['time','status']);expect(conflict.factors.find(f=>f.key==='conflict')?.points).toBeLessThan(0);expect(conflict.evidence).toHaveLength(2);});
 it('requires an advertised same-domain organizer channel',()=>{expect(evidenceFromHappening(h({rawMetadata:{organizer:'Named organizer'}})).role).toBe('publisher');expect(evidenceFromHappening(h({rawMetadata:{organizerUrl:'https://venue.example/about'}})).role).toBe('organizer');expect(evidenceFromHappening(h({rawMetadata:{organizerUrl:'https://other.example/'}})).role).toBe('publisher');});
 it('preserves stable publisher identities but records real changes',()=>{const first=h();const changed=h({id:'new-time-id',startTime:'2026-10-02T20:00:00Z'});expect(samePublisherIdentity(first,changed)).toBe(true);expect(sameResearchSubject(first,changed)).toBe(true);expect(meaningfulChanges(first,{...first,updatedAt:'2026-10-01T00:00:00Z',lastVerifiedAt:'2026-10-01T00:00:00Z'})).toEqual([]);const db=new LocalDatabase(':memory:');db.saveSettings({...defaultSettings,onboarded:true});db.ingest([first]);db.toggleSaved(first.id);expect(db.ingest([changed]).updated).toBe(1);expect(db.getState().happenings).toHaveLength(1);expect(db.getState().savedIds).toEqual(['event']);expect(db.getState().intelligence?.history.some(e=>e.changes?.some(c=>c.field==='startTime'))).toBe(true);expect(db.ingest([{...changed,lastVerifiedAt:'2026-10-01T00:00:00Z'}]).updated).toBe(0);db.close();});
 it('accepts actual public posts without inventing event dates',()=>{const valid={uri:'at://did:plc:abc/app.bsky.feed.post/xyz',author:{did:'did:plc:abc',handle:'local.example'},record:{text:'Fishers community meetup announced',createdAt:now}};expect(parsePublicPosts({posts:[valid,{...valid,author:{did:'did:plc:wrong'}},{...valid,record:{text:'claim',createdAt:'invalid'}}]})).toHaveLength(1);expect(parsePublicPosts({posts:[valid]})[0].startTime).toBeUndefined();});
 it('counts observed publishers and labels nearby impacts as possible',()=>{const records=[h(),h({id:'closure',category:'traffic',latitude:h().latitude,longitude:h().longitude,locationName:'Nearby road'})];const coverage=calculateCoverage({settings:defaultSettings,happenings:records,sources:[],radars:[],savedIds:[]},now);expect(coverage.categories.find(c=>c.category==='music')?.healthy).toBe(0);expect(coverage.explanation).toContain('does not measure all activity');expect(observedRelationships(records)[0]?.reason).toContain('possible impact');});
});
